name: 'Setup NPM'
description: 'Configure access to artifactory'
runs:
  using: "composite"
  steps:    
    - run: touch ~/.npmrc
    - run: echo tag-version-prefix= >> ~/.npmrc
    - run: echo @focus:registry=https://artifactory.dimensiondata.com/artifactory/api/npm/npm/ >> ~/.npmrc
    - run: echo @insight:registry=https://artifactory.dimensiondata.com/artifactory/api/npm/npm/ >> ~/.npmrc
    - run: echo @sp:registry=https://artifactory.dimensiondata.com/artifactory/api/npm/npm/ >> ~/.npmrc
    - run: echo //artifactory.dimensiondata.com/artifactory/api/npm/npm/:_auth=$ARTIFACTORY_AUTH >> ~/.npmrc
    - run: echo //artifactory.dimensiondata.com/artifactory/api/npm/npm/:always-auth=true >> ~/.npmrc
    - run: echo //artifactory.dimensiondata.com/artifactory/api/npm/npm/:email=$ARTIFACTORY_EMAIL >> ~/.npmrc