name: Unit Test
on: [push]
jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    environment: action
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: ./.github/actions/setup-auth      
        env:
            ARTIFACTORY_AUTH: ${{ secrets.ARTIFACTORY_AUTH }}
            ARTIFACTORY_EMAIL: ${{ secrets.ARTIFACTORY_EMAIL }}
            SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: npm ci
      - run: npm test