name: Unit Test
on: [push]
jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    environment: action
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: echo scm.dimensiondata.com,185.3.28.79 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEDNMvCZVMIHWZuIgoXWg0zHOo6mIdPYptyK1IiYkRvr >> ~/.ssh/known_hosts
      - uses: ./.github/actions/setup-auth      
        env:
            ARTIFACTORY_AUTH: ${{ secrets.ARTIFACTORY_AUTH }}
            ARTIFACTORY_EMAIL: ${{ secrets.ARTIFACTORY_EMAIL }}
            SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      - run: npm ci
      - run: npm test