name: Unit Test
on: [push]
jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: ./.github/actions/setup-npm
      # - run: npm ci
      # - run: npm test